../../../bin/ledger-txt bad.txt  ../condensed/bad.txt
../../../bin/ledger-txt bad2.txt  ../condensed/bad2.txt
../../../bin/ledger-txt basic.txt  ../condensed/basic.txt
../../../bin/ledger-txt empty.txt  ../condensed/empty.txt
../../../bin/ledger-txt example_ledger.txt  ../condensed/example_ledger.txt
../../../bin/ledger-txt justbank.txt  ../condensed/justbank.txt
../../../bin/ledger-txt justcredit.txt  ../condensed/justcredit.txt
../../../bin/ledger-txt nonnull.txt  ../condensed/nonnull.txt
../../../bin/ledger-txt small.txt  ../condensed/small.txt