../../../bin/ledger-txt bad.txt &> ../summaries/bad.txt
../../../bin/ledger-txt bad2.txt &> ../summaries/bad2.txt
../../../bin/ledger-txt basic.txt &> ../summaries/basic.txt
../../../bin/ledger-txt empty.txt &> ../summaries/empty.txt
../../../bin/ledger-txt example_ledger.txt &> ../summaries/example_ledger.txt
../../../bin/ledger-txt justbank.txt &> ../summaries/justbank.txt
../../../bin/ledger-txt justcredit.txt &> ../summaries/justcredit.txt
../../../bin/ledger-txt nonnull.txt &> ../summaries/nonnull.txt
../../../bin/ledger-txt small.txt &> ../summaries/small.txt